# makefile.vc

# dder.exe makefile for Microsoft Visual C
# Tested on MSVC2013

# Sébastien Millet, Februay 2015

CPP = cl.exe
CPPFLAGS = /Ox /W2
LINKERFLAGS = /Ox /W2

all : dder.exe

dder.exe : dder.obj
	$(CPP) $(LINKERFLAGS) dder.obj

dder.obj : src\dder.c
	$(CPP) $(CPPFLAGS) -c src\dder.c

mrproper : clean

clean :
	del *.obj 2>NUL
	del dder.exe 2>NUL

