# makefile.vc

# dder.exe makefile for Microsoft Visual C
# Tested on MSVC2013

# Sébastien Millet, Februay 2015

CPP = cl.exe
CPPFLAGS = -Wall
LINKERFLAGS = -Wall
OFLAG = -o

.SUFFIXES : .obj .cpp .h
.cpp.obj :
	$(CPP) $(CPPFLAGS) -c $<

all : dder.exe

dder.exe : dder.obj
	$(CPP) $(LINKERFLAGS) $(OFLAG)dder dder.obj

dder.obj : dder.c

clean :
	del *.obj 2>NUL
	del dder.exe 2>NUL

